### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by xlin084** [EmergencyNumberAPI/issues#5]
Hi team,

just a friendly reminder that the SSL certificate seems expired.
<img width="860" alt="image" src="https://user-images.githubusercontent.com/39845869/197084503-133b0fb6-8aee-4504-a296-fb24dd98a52f.png">

Many thanks,

**Comment by johnnye** [comment]
Not sure why that didn't auto-renew. But should be fixed now.
